### ISSUE TITLE
Ease complete notification

### ISSUE THREAD

**Issue by whiteangle** [roberthein/Ease#2]
Hi, thanks for the great utility. I’m trying to execute some code once the spring animation is complete so trying to work out how best to get notified that the Ease isPaused or has reached the target value.

**Comment by roberthein** [comment]
Yes!! I want this too. I’m currently traveling but will add it when I’m back.

**Comment by whiteangle** [comment]
Cool. That would be awesome

**Comment by whiteangle** [comment]
bump :)

**Comment by roberthein** [comment]
I finally got around to adding this. So please update to 3.1.0 and let me know if it's what you expected. ❤️

**Comment by whiteangle** [comment]
Awesome, thanks Robert. 

Will take a look. 

Adam
