### ISSUE TITLE
compile error in Example 3D (Easy3DSceneKit/GameViewController.swift)

### ISSUE THREAD

**Issue by lingolab2** [roberthein/Ease#3]
Noticed a compile-error:
line 69: Easy3DSceneKit/GameViewController.swift
Extra argument 'damping' in call

ease.addSpring(tension: tension, damping: damping, mass: mass) { point, _ in
                childNode.runAction(SCNAction.rotateTo(x: point.y / 35, y: point.x / 250, z: 0, duration: 0))
                }.add(to: &disposal)

similar error in Example project as well.

**Comment by roberthein** [comment]
You are absolutely right @lingolab2!
I broke this with the latest update, but it's fixed now! Thanks for noticing! 🤗
